# Generated by Django 6.0.4 on 2026-04-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmetadata',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
